baseURL = "https://jhagan-cyber-blog.pages.dev/"
languageCode = "en-us"
title = "NullByte Notes"

theme = "PaperMod"

[params]
defaultTheme = "dark"
ShowReadingTime = false
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
disableSpecial1stPost = true

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "writeups"
name = "Writeups"
url = "/writeups/"
weight = 2

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 3

[[menu.main]]
identifier = "tools"
name = "Tools"
url = "/tools/"
weight = 4

[[menu.main]]
identifier = "certifications"
name = "Certifications"
url = "/certifications/"
weight = 5

[[menu.main]]
identifier = "news"
name = "News"
url = "/news/"
weight = 6

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 7
